# Generated by Django 5.0.4 on 2026-04-14 05:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outbox_events',
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbox_even_status_8ec420_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='outbox_even_aggrega_d56a15_idx'), models.Index(fields=['event_type'], name='outbox_even_event_t_4c1832_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('consumer_name', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processed_events',
                'indexes': [models.Index(fields=['consumer_name', 'processed_at'], name='processed_e_consume_5408fc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='processedevent',
            constraint=models.UniqueConstraint(fields=('event_id', 'consumer_name'), name='unique_processed_event_per_consumer'),
        ),
    ]
