# Generated by Django 5.0.4 on 2026-04-14 05:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_failed', 'Order Failed'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('event_id', models.UUIDField()),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_dee16f_idx'), models.Index(fields=['event_id'], name='notificatio_event_i_d4c705_idx')],
            },
        ),
    ]
